-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 22:09:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb2` DEFAULT CHARACTER SET utf8 ;
USE `mydb2` ;

-- -----------------------------------------------------
-- Table `mydb2`.`Adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Adress` (
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `x` INT NULL,
  `y` INT NULL,
  PRIMARY KEY (`adress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`User` (
  `userName` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` INT NULL,
  `phone` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `Adress_adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userName`),
  INDEX `fk_User_Adress1_idx` (`Adress_adress` ASC) VISIBLE,
  CONSTRAINT `fk_User_Adress1`
    FOREIGN KEY (`Adress_adress`)
    REFERENCES `mydb2`.`Adress` (`adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`ItemList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`ItemList` (
  `idItemList` INT NOT NULL,
  `clothes` INT NULL,
  `furniture` INT NULL,
  `books` INT NULL,
  `toys` INT NULL,
  PRIMARY KEY (`idItemList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Charity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Charity` (
  `User_userName` VARCHAR(45) NOT NULL,
  `acceptable_ItemList_idItem` INT NOT NULL,
  `webpage` VARCHAR(45) NULL,
  `description` VARCHAR(450) NULL,
  PRIMARY KEY (`User_userName`),
  INDEX `fk_Charity_ItemList1_idx` (`acceptable_ItemList_idItem` ASC) VISIBLE,
  INDEX `fk_Charity_User1_idx` (`User_userName` ASC) VISIBLE,
  CONSTRAINT `fk_Charity_ItemList1`
    FOREIGN KEY (`acceptable_ItemList_idItem`)
    REFERENCES `mydb2`.`ItemList` (`idItemList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Charity_User1`
    FOREIGN KEY (`User_userName`)
    REFERENCES `mydb2`.`User` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Driver` (
  `User_userName` VARCHAR(45) NOT NULL,
  `hours` DOUBLE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`User_userName`),
  CONSTRAINT `fk_Driver_User1`
    FOREIGN KEY (`User_userName`)
    REFERENCES `mydb2`.`User` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Task` (
  `idTask` INT NOT NULL,
  `pickupAdress` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `description` VARCHAR(300) NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  `ItemList_idItemList` INT NOT NULL,
  `Driver_User_userName` VARCHAR(45) NOT NULL,
  `Charity_User_userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_User1_idx` (`User_userName` ASC) VISIBLE,
  INDEX `fk_Task_ItemList1_idx` (`ItemList_idItemList` ASC) VISIBLE,
  INDEX `fk_Task_Driver1_idx` (`Driver_User_userName` ASC) VISIBLE,
  INDEX `fk_Task_Charity1_idx` (`Charity_User_userName` ASC) VISIBLE,
  CONSTRAINT `fk_Task_User1`
    FOREIGN KEY (`User_userName`)
    REFERENCES `mydb2`.`User` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_ItemList1`
    FOREIGN KEY (`ItemList_idItemList`)
    REFERENCES `mydb2`.`ItemList` (`idItemList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Driver1`
    FOREIGN KEY (`Driver_User_userName`)
    REFERENCES `mydb2`.`Driver` (`User_userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Charity1`
    FOREIGN KEY (`Charity_User_userName`)
    REFERENCES `mydb2`.`Charity` (`User_userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
